name: PR Welcome Message 2

on:
  pull_request_target:
    types: [opened]  # This workflow triggers when a pull request is opened.

permissions:
  issues: write

jobs:
  new_welcome_message:
    runs-on: ubuntu-latest  # Specifies the runner.

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Leave a comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = "Writing from Actions";
            github.rest.issues.createComment({
              owner: "SuttGHA",
              repo: "my-gha-1",
              issue_number: "6",
              body: message
            });
        # with:
        #   github-token: ${{secrets.GITHUB_TOKEN}}
        #   script: |
        #     const issue_number = context.payload.pull_request.number;
        #     const owner = context.repo.owner;
        #     const repo = context.repo.repo;
        #     const message = "Thank you for your contribution! We will review it as soon as possible. 😊";
        #     github.rest.issues.createComment({
        #       owner,
        #       repo,
        #       issue_number,
        #       body: message
        #     });
